<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="2" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Larning testNG" duration-ms="446" started-at="2017-06-20T09:56:20Z" finished-at="2017-06-20T09:56:21Z">
    <groups>
    </groups>
    <test name="Application Test" duration-ms="15" started-at="2017-06-20T09:56:20Z" finished-at="2017-06-20T09:56:20Z">
      <class name="testcases.ApplicationTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="beforemethod" is-config="true" duration-ms="1" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="doLogin()[pri:1, instance:testcases.ApplicationTest@402f32ff]" name="doLogin" duration-ms="2" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Error Message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Error Message
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.ApplicationTest.doLogin(ApplicationTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="AfterMethod" is-config="true" duration-ms="0" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="SKIP" signature="doPasswordChange()[pri:2, instance:testcases.ApplicationTest@402f32ff]" name="doPasswordChange" duration-ms="0" started-at="2017-06-20T15:26:20Z" depends-on-methods="testcases.ApplicationTest.doLogin" finished-at="2017-06-20T15:26:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ApplicationTest.doPasswordChange()[pri:2, instance:testcases.ApplicationTest@402f32ff] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ApplicationTest.doPasswordChange()[pri:2, instance:testcases.ApplicationTest@402f32ff] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doPasswordChange -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="doLogout()[pri:3, instance:testcases.ApplicationTest@402f32ff]" name="doLogout" duration-ms="0" started-at="2017-06-20T15:26:20Z" depends-on-methods="testcases.ApplicationTest.doLogin, testcases.ApplicationTest.doPasswordChange" finished-at="2017-06-20T15:26:20Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ApplicationTest.doLogout()[pri:3, instance:testcases.ApplicationTest@402f32ff] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ApplicationTest.doLogout()[pri:3, instance:testcases.ApplicationTest@402f32ff] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogout -->
      </class> <!-- testcases.ApplicationTest -->
    </test> <!-- Application Test -->
    <test name="Login Test" duration-ms="2" started-at="2017-06-20T09:56:20Z" finished-at="2017-06-20T09:56:20Z">
      <class name="testcases.LoginTest">
        <test-method status="SKIP" signature="doLoginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.LoginTest@735b5592]" name="doLoginTest" duration-ms="0" started-at="2017-06-20T15:26:20Z" data-provider="getData" finished-at="2017-06-20T15:26:20Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/google/common/primitives/Ints
	at org.testng.internal.annotations.JDK15TagFactory.createDataProviderTag(JDK15TagFactory.java:335)
	at org.testng.internal.annotations.JDK15TagFactory.createTag(JDK15TagFactory.java:59)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:217)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:111)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:326)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:261)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1240)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
Caused by: java.lang.ClassNotFoundException: com.google.common.primitives.Ints
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test name="Registration Test" duration-ms="314" started-at="2017-06-20T09:56:20Z" finished-at="2017-06-20T09:56:21Z">
      <class name="testcases.ApplicationTest">
        <test-method status="PASS" signature="beforesuite()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="beforesuite" is-config="true" duration-ms="16" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforesuite -->
        <test-method status="PASS" signature="aftersuite()[pri:0, instance:testcases.ApplicationTest@402f32ff]" name="aftersuite" is-config="true" duration-ms="0" started-at="2017-06-20T15:26:21Z" finished-at="2017-06-20T15:26:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite -->
      </class> <!-- testcases.ApplicationTest -->
      <class name="testcases.RegTest">
        <test-method status="FAIL" signature="doRegisterTest()[pri:0, instance:testcases.RegTest@675d3402]" name="doRegisterTest" duration-ms="6" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [jdjfg] but found [fhdj],
	expected [B] but found [A]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [jdjfg] but found [fhdj],
	expected [B] but found [A]
	at org.testng.Assert.fail(Assert.java:94)
	at testcases.RegTest.doRegisterTest(RegTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doRegisterTest -->
        <test-method status="PASS" signature="Quit()[pri:0, instance:testcases.RegTest@675d3402]" name="Quit" is-config="true" duration-ms="307" started-at="2017-06-20T15:26:20Z" finished-at="2017-06-20T15:26:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quit -->
      </class> <!-- testcases.RegTest -->
    </test> <!-- Registration Test -->
  </suite> <!-- Larning testNG -->
</testng-results>
